### ISSUE TITLE
Make q provider pluggable

### ISSUE THREAD

**Issue by c0c0n3** [openmicroscopy/omero-ms-queue#3]
The [messaging API][msg] is built on top of a few primitive interfaces---classes in [core.msg package][msg-pkg]. A separate queue provider package provides an implementation of those primitive interfaces using Artemis---classes in [providers.q package][q-provider]. We should make the `q` package pluggable so that we can use different implementations along the current one based on Artemis. 

So for example, going forward we should be able to easily add a `q` implementation backed by RabbitMQ or even one that uses (abuses?) Vert.x's event bus to provide an implementation of the abstract communication channels in the `msg` package.

[msg]: http://c0c0n3.github.io/ome-smuggler/docs/content/design/messaging/index.html
[msg-pkg]: https://github.com/openmicroscopy/omero-ms-queue/tree/master/components/server/src/main/java/ome/smuggler/core/msg
[q-provider]: https://github.com/openmicroscopy/omero-ms-queue/tree/master/components/server/src/main/java/ome/smuggler/providers/q

**Comment by joshmoore** [comment]
From my point-of-view, the two top priorities for backends should cover:

 * the vanilla install that anyone with a single VM can manage
 * _some_ distributed (i.e. multi-VM) setup

Don't need to go too much farther than that initially.

**Comment by c0c0n3** [comment]
Most definitely yes! In fact, I need to have the single VM install option to support the deployment model here at MRI. Re: queue distribution, this is a low hanging fruit, so we should have that too. (The default being the all-in-one option like you said.)
